SOURCES = [
    {"name": "ASCE Civil Engineering Source", "url": "https://www.asce.org/publications-and-news/civil-engineering-source/rss", "type": "rss", "category_hint": "Structures", "language": "en"},
    {"name": "Engineering News-Record", "url": "https://www.enr.com/rss", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "New Civil Engineer", "url": "https://www.newcivilengineer.com/feed/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "The Constructor", "url": "https://theconstructor.org/feed/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Construction Dive", "url": "https://www.constructiondive.com/feeds/news/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "ScienceDaily Civil Engineering", "url": "https://www.sciencedaily.com/rss/matter_energy/civil_engineering.xml", "type": "rss", "category_hint": "Innovation", "language": "en"},
    {"name": "Institution of Civil Engineers", "url": "https://www.ice.org.uk/news-insight/rss", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "The Construction Index", "url": "https://www.theconstructionindex.co.uk/news/rss", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Construction Management / CIOB", "url": "https://constructionmanagement.co.uk/feed/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Roads & Bridges", "url": "https://www.roadsbridges.com/rss.xml", "type": "rss", "category_hint": "Routes", "language": "en"},
    {"name": "Concrete Construction", "url": "https://www.concreteconstruction.net/rss", "type": "rss", "category_hint": "Béton", "language": "en"},
    {"name": "World Highways", "url": "https://www.worldhighways.com/rss.xml", "type": "rss", "category_hint": "Routes", "language": "en"},
    {"name": "Global Construction Review", "url": "https://www.globalconstructionreview.com/feed/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "Construction Europe", "url": "https://www.construction-europe.com/rss", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Engineering.com", "url": "https://www.engineering.com/feed/", "type": "rss", "category_hint": "Innovation", "language": "en"},
    {"name": "Autodesk AEC / BIM Blog", "url": "https://www.autodesk.com/blogs/aec/feed/", "type": "rss", "category_hint": "BIM / Revit", "language": "en"},
    {"name": "BIM Today", "url": "https://www.pbctoday.co.uk/news/category/bim-news/feed/", "type": "rss", "category_hint": "BIM / Revit", "language": "en"},
    {"name": "Civil Engineering Magazine / ASCE", "url": "https://www.asce.org/publications-and-news/civil-engineering-magazine/rss", "type": "rss", "category_hint": "Structures", "language": "en"},
    {"name": "Construction & Civil Engineering Magazine", "url": "https://ccemagazine.com/feed/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Infrastructure Intelligence", "url": "https://www.infrastructure-intelligence.com/rss.xml", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
]
