SOURCES = [
    {"name": "ASCE Civil Engineering Source", "url": "https://www.asce.org/publications-and-news/civil-engineering-source", "type": "html", "category_hint": "Structures", "language": "en"},
    {"name": "New Civil Engineer", "url": "https://www.newcivilengineer.com/feed/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "The Constructor", "url": "https://theconstructor.org/feed/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Construction Dive", "url": "https://www.constructiondive.com/feeds/news/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "ScienceDaily Civil Engineering", "url": "https://www.sciencedaily.com/rss/matter_energy/civil_engineering.xml", "type": "rss", "category_hint": "Innovation", "language": "en"},
    {"name": "The Construction Index", "url": "https://www.theconstructionindex.co.uk/news/rss", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Construction Management / CIOB", "url": "https://constructionmanagement.co.uk/feed/", "type": "rss", "category_hint": "Sécurité chantier", "language": "en"},
    {"name": "Roads & Bridges", "url": "https://www.roadsbridges.com/", "type": "html", "category_hint": "Routes", "language": "en"},
    {"name": "Concrete Construction", "url": "https://www.concreteconstruction.net/rss", "type": "rss", "category_hint": "Béton", "language": "en"},
    {"name": "World Highways", "url": "https://www.worldhighways.com/rss.xml", "type": "rss", "category_hint": "Routes", "language": "en"},
    {"name": "Global Construction Review", "url": "https://www.globalconstructionreview.com/feed/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "Engineering.com", "url": "https://www.engineering.com/feed/", "type": "rss", "category_hint": "Innovation", "language": "en"},
    {"name": "BIM Today", "url": "https://www.pbctoday.co.uk/news/category/bim-news/feed/", "type": "rss", "category_hint": "BIM / Revit", "language": "en"},
    {"name": "Construction & Civil Engineering Magazine", "url": "https://ccemagazine.com/feed/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "World Construction Network", "url": "https://www.worldconstructionnetwork.com/feed/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "International Construction", "url": "https://www.international-construction.com/rss", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Construction Technology", "url": "https://www.constructiontechnology.media/feed/", "type": "rss", "category_hint": "Innovation", "language": "en"},
    {"name": "Building Design + Construction", "url": "https://www.bdcnetwork.com/", "type": "html", "category_hint": "Construction", "language": "en"},
    {"name": "For Construction Pros", "url": "https://www.forconstructionpros.com/rss", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Railway Technology", "url": "https://www.railway-technology.com/feed/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "Airport Technology", "url": "https://www.airport-technology.com/feed/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "Water Technology", "url": "https://www.water-technology.net/feed/", "type": "rss", "category_hint": "Hydraulique", "language": "en"},
    {"name": "World Cement", "url": "https://www.worldcement.com/", "type": "html", "category_hint": "Béton", "language": "en"},
    {"name": "Cement Optimized", "url": "https://cementoptimized.com/", "type": "html", "category_hint": "Matériaux", "language": "en"},
    {"name": "Geoengineer", "url": "https://www.geoengineer.org/news", "type": "html", "category_hint": "Géotechnique", "language": "en"},
    {"name": "BridgeWeb", "url": "https://www.bridgeweb.com/", "type": "html", "category_hint": "Ponts", "language": "en"},
    {"name": "Construction Specifier", "url": "https://www.constructionspecifier.com/feed/", "type": "rss", "category_hint": "Matériaux", "language": "en"},
    {"name": "AEC Magazine", "url": "https://aecmag.com/feed/", "type": "rss", "category_hint": "BIM / Revit", "language": "en"},
    {"name": "BuiltWorlds", "url": "https://builtworlds.com/feed/", "type": "rss", "category_hint": "Innovation", "language": "en"},
    {"name": "PBC Today", "url": "https://www.pbctoday.co.uk/news/feed/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Highways Today", "url": "https://highways.today/feed/", "type": "rss", "category_hint": "Routes", "language": "en"},
    {"name": "International Railway Journal", "url": "https://www.railjournal.com/feed/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "STRUCTURE Magazine", "url": "https://www.structuremag.org/feed/", "type": "rss", "category_hint": "Structures", "language": "en"},
    {"name": "Civil Engineering Portal", "url": "https://www.engineeringcivil.com/feed", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "GeoPrac", "url": "https://geoprac.net/feed/", "type": "rss", "category_hint": "Géotechnique", "language": "en"},
    {"name": "Trenchless Works", "url": "https://www.trenchless-works.com/feed/", "type": "rss", "category_hint": "Hydraulique", "language": "en"},
    {"name": "Ground Engineering", "url": "https://www.geplus.co.uk/feed/", "type": "rss", "category_hint": "Géotechnique", "language": "en"},
    {"name": "Smart Cities Dive", "url": "https://www.smartcitiesdive.com/feeds/news/", "type": "rss", "category_hint": "Infrastructures", "language": "en"},
    {"name": "Construction Canada", "url": "https://www.constructioncanada.net/feed/", "type": "rss", "category_hint": "Construction", "language": "en"},
    {"name": "Construction Briefing", "url": "https://www.constructionbriefing.com/", "type": "html", "category_hint": "Construction", "language": "en"},
]
